[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Align'

[[plugins]]
repo = "vim-ruby/vim-ruby"
on_ft = "ruby"

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = "ruby"

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = "slim"

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'rodjek/vim-puppet'

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = "coffee"

[[plugins]]
repo = 'soramugi/auto-ctags.vim'

[[plugins]]
repo = 'AndrewRadev/switch.vim'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = "tpope/vim-endwise"

[[plugins]]
repo = "jiangmiao/auto-pairs"

[[plugins]]
repo = "pangloss/vim-javascript"
on_ft = ["javascript", "javascript.jsx"]

[[plugins]]
#repo = "maxmellon/vim-jsx-pretty"
repo = "mxw/vim-jsx"
on_ft = ["javascript", "javascript.jsx"]

[[plugins]]
repo = "derekwyatt/vim-scala"
on_ft = "scala"

[[plugins]]
repo = "Shougo/vimproc"
build = "make"

[[plugins]]
repo = "tpope/vim-fugitive"

[[plugins]]
repo = "kassio/neoterm"
if = '''has('nvim')'''

[[plugins]]
repo = "cespare/vim-toml"
on_f = "toml"

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'rust-lang/rust.vim'
on_f = "rust"

[[plugins]]
repo = 'racer-rust/vim-racer'
on_f = "rust"

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_f = ["typescript", "typescript.tsx"]

[[plugins]]
repo = 'hashivim/vim-terraform'
on_f = ['terraform']

[[plugins]]
repo = 'maximbaz/lightline-ale'
depends = ['lightline.vim', 'ale']

[[plugins]]
repo = 'tfnico/vim-gradle'
on_ft = ['gradle', 'groovy']

[[plugins]]
repo = 'vim-scripts/groovy.vim'
on_ft = 'groovy'

[[plugins]]
repo = "udalov/kotlin-vim"
on_ft = ["kt", "kts"]
