#!/usr/local/bin/zsh
for c in {000..255}; do
  echo -n "\e[38;5;${c}m $c"
  [ $(($c%16)) -eq 15 ] && echo
done

for c in {000..255}; do
  echo -n "\e[30;48;5;${c}m $c\e[0m"
  [ $(($c%16)) -eq 15 ] && echo
done

#for c in {000..255}; do
#  echo -n "\e[38;5;${c};48;5;${c}m $c\e[0m"
#  [ $(($c%16)) -eq 15 ] && echo
#done
